language: node_js
node_js:
- '6'
- '7'
- '8'
- '9'
deploy:
  provider: npm
  email: hello@freethinking.it
  api_key:
    secure: AL0+UIdro5it6u6glM5dsvN8LeMVgu7NxFsOlBLAdDpJ4agxJO4obmSUE7Ct7hnkBoLzobmN7itJEXiMs5KJx+XXvkPusHGXBkXzKXUdMwQ3EuBHIX3jgHMVcfR+8l3VO+PmBwG2nMtnnXIqw5PnAlC1bYHolBRCi/O+U6fSC6F2c+wSvIlNBGkqZ4NJV4gL5T9bCzFkDjz3W9NyptJIitANt6B8wEVY3c/ghZVm9fX29GuENnbV/SIa93RlGxuHTerxU9n0tnq6sJ+zsgZHowsnkI+GgORIdqLmXT5Hex6fsbQEODUydLtvu9GrKUJEyvU1nUooI90+5Pvc6okdHjf5+NOzJp63gGDvWJ6LTgKfP0G321S/WwgWLYddu09f0Bk9hKiOS+PqT47Ig3A1FXZuYfqUqPIe4XRbjfO97eI56P5K/dQjam8DOUiBYUW8FRq3P3HmTJa4m6Kw/OMWsdy/8fBc1NzIQu8dBdzz3dfMf5myhbDsQSLUCVC6CCjOez8SttjHHrKCix9hm29VV41vSPB3S5PTVdr5ru6oUfHL/nqMQxG7W2PYb6TaNEYjSa3Yg/g7PaTsmolLEJH+S7z1sZOIUJ6cPqCRzRSze6b4WqrO94y3ZeKngieatlOlJBxHQQbrLM4xa2rsckan7j8cUgcJzmNNR0jTpGkXUU0=
  on:
    tags: true
    repo: freethinkingit/inline-email
